name = "hotel-chat-worker"
main = "src/index.ts"
compatibility_date = "2024-10-25"
compatibility_flags = ["nodejs_compat"]

# KV namespace for session storage
[[kv_namespaces]]
binding = "CHAT_SESSIONS"
id = "90e1d327acd344a39fd5c575e4d6d949"
preview_id = "90e1d327acd344a39fd5c575e4d6d949"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[vars]
# Langfuse
LANGFUSE_HOST = "https://cloud.langfuse.com"
LANGFUSE_PUBLIC_KEY = "pk-lf-2e97d260-a63c-45cb-89ac-2b66c085840c"

# Google Sheets
GOOGLE_SHEETS_DOCUMENT_ID = "1lx-s6rxPGn4IKgFQk7vrtO4nDH0diHE1dr04u8b6dx4"

# Email
RESEND_FROM_EMAIL = "Hotel Guest Service <ai.agent@pragmaticcoders.com>"

# Session
CONTEXT_WINDOW_LENGTH = "15"