name = "hotel-chat-worker"
main = "src/index.ts"
compatibility_date = "2024-10-25"

# KV namespace for session storage
[[kv_namespaces]]
binding = "CHAT_SESSIONS"
id = "1142c6a3e16d49e29161c0cfad093766"
preview_id = "1142c6a3e16d49e29161c0cfad093766"